final houseList = [
  {
    'image': 'assets/images/properties/dwell_1.png',
    'name': 'Skyline Penthouse',
    'address': '1049 5th Av, New York',
    'bedrooms': '4',
    'bathrooms': '3',
    'squareFeet': '2,400',
    'price': '\$10,000',
  },
  {
    'image': 'assets/images/properties/dwell_2.png',
    'name': 'Riverside Villa',
    'address': '221B Baker St, London',
    'bedrooms': '3',
    'bathrooms': '2',
    'squareFeet': '1,800',
    'price': '\$7,500',
  },
  {
    'image': 'assets/images/properties/dwell_3.png',
    'name': 'Coastal Paradise',
    'address': '12 Ocean Drive, Miami',
    'bedrooms': '4',
    'bathrooms': '3',
    'squareFeet': '1,650',
    'price': '\$5,500',
  },
  {
    'image': 'assets/images/properties/dwell_4.png',
    'name': 'Mountain Retreat',
    'address': '742 Evergreen Forest, Springfield',
    'bedrooms': '3',
    'bathrooms': '2',
    'squareFeet': '3,200',
    'price': '\$12,000',
  },
  {
    'image': 'assets/images/properties/dwell_5.png',
    'name': 'Desert Oasis',
    'address': '3500 Canyon Rd, Salt Lake City, Utah',
    'bedrooms': '5',
    'bathrooms': '4',
    'squareFeet': '3,500',
    'price': '\$9,800',
  },
  {
    'image': 'assets/images/properties/dwell_6.png',
    'name': 'Charming Flat',
    'address': '15 Abbey Rd, London',
    'bedrooms': '2',
    'bathrooms': '1',
    'squareFeet': '950',
    'price': '\$4,200',
  },
];
